# Use older, non-container infrastructure to allow sudo
sudo: required

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy

# Travis CI support for Python 3.7 currently requires patch (https://github.com/travis-ci/travis-ci/issues/9815)
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

env:
  - BUILD_CAPNP=
  - BUILD_CAPNP=true
  - BUILD_CAPNP=true CFLAGS="-DKJ_DEBUG"

# skip testing for pypy + BUILD_CAPNP=false since it's failing in travis for some reason
matrix:
  exclude:
    - python: pypy
      env: BUILD_CAPNP=

compiler: gcc

before_install:
  - buildutils/setup_travis.sh
  - travis_retry pip install -U setuptools
  - travis_retry pip install cython==0.21.2
  - travis_retry pip install pytest

install:
  - travis_retry pip install --editable .

script: py.test test;
